AWSTemplateFormatVersion: "2010-09-09"
Description: Product Sorter — Secrets Manager

Parameters:
  MongoUri:
    Type: String
    Description: The MongoDB URI
    NoEcho: true

Resources:
  MongoUriSecret:
    Type: AWS::SecretsManager::Secret
    Description: "Mongo URI"
    DeletionPolicy: Delete
    Properties:
      Name: "MongoUri"
      Description: "Mongo URI"
      SecretString: !Sub '{"uri":"${MongoUri}"}'

Outputs:
  MongoUriSecretArn:
    Value: !Ref MongoUriSecret
    Description: ARN of the MongoDB URI secret
    Export:
      Name: MongoUriSecretArn
