global:
  scrape_interval: 5s

scrape_configs:
  - job_name: product-sorter
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["product-sorter-app:8880", "host.docker.internal:8880"]
