name: Code Mirroring

on:
  push:
    branches: [develop]

concurrency:
  group: mirroring
  cancel-in-progress: false

jobs:
  mirror:
    environment: pro
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
        with: { fetch-depth: 0 }
      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab "https://gitlab.com/side-projects9205424/product-sorter.git"
          git config --local url."https://oauth2:${GITLAB_TOKEN}@gitlab.com".insteadOf "https://gitlab.com"
          git push gitlab develop --force --prune
          git push gitlab --tags --force
      - name: Push to Bitbucket
        env:
          BITBUCKET_USER: ${{ secrets.BITBUCKET_USER }}
          BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
        run: |
          git remote add bitbucket "https://bitbucket.org/jpje-side-projects/product-sorter.git"
          git config --local url."https://${BITBUCKET_USER}:${BITBUCKET_TOKEN}@bitbucket.org".insteadOf "https://bitbucket.org"
          git push bitbucket develop --force --prune
          git push bitbucket --tags --force
